# Generated by Django 2.1.5 on 2019-01-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generaluser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
