# Generated by Django 2.1.5 on 2019-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaluser', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='NO_USER', max_length=255),
            preserve_default=False,
        ),
    ]
