# Generated by Django 2.1.5 on 2019-01-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaluser', '0004_auto_20190120_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doctor',
            field=models.BooleanField(default=False),
        ),
    ]
