# Generated by Django 2.1.5 on 2019-01-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaluser', '0005_auto_20190120_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=True),
        ),
    ]
